# Generated by Django 4.2.5 on 2023-09-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABACStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('previous_institute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MSMEStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('certificate', models.CharField(max_length=50)),
                ('abac_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop2_app.abacstudent')),
            ],
        ),
    ]
