# Generated by Django 4.2.5 on 2023-09-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
